name: General Issue
description: Issue that is difficult to fit into bug, feature or documentation issue.
title: "General Issue: <Insert Issue Title Here>"
labels: ["general issue"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **Example:** General Issue: What happens when a new ADaM-IG is released?
  - type: textarea
    id: background
    attributes:
      label: Background Information
      description: Please provide the context and purpose of this piece of work. Links and screenshots are encouraged.     
      placeholder: "The more information the better and the faster we can get this issue completed."
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      description: Please define the deliverable or the desired outcome.
      placeholder: "Example:  All changes since last release are highlighted in News.md file."
    validations:
      required: false
